/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs643.spark.wine;

import java.io.IOException;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {

        String trainDataPath = args[0];
        String validationDataPath = args[1];
        String sparkMaster = args[2];
        
        var workingDir = System.getProperty("user.dir");
        logger.info("Working directory: {}", workingDir);
        var model1 = new LRClassifier(sparkMaster, null);
        model1.setTrainingData(trainDataPath);
        model1.setValidationData(validationDataPath);
        ClassifierResult result1 = model1.evaluate();


        // var model2 = new RFClassifier(sparkMaster, null);
        // model2.setTrainingData(trainDataPath);
        // model2.setValidationData(validationDataPath);
        // ClassifierResult result2 = model2.evaluate();

        // System.out.println("Logistic Regression");
        // System.out.println(result1.toString());
        // System.out.println("Random Forest");
        // System.out.println(result2.toString());

        // try {
        //     model1.pipeline.write().overwrite().save("./model/traindedModel");
        // } catch (IOException e) {
        //     logger.error("Could NOT save the model to path ./models/", e);
        // }

    }
}
